template-file-path: './infrastructure/production/s3bucket.yaml'

parameters:
  S3BucketPrefixName: 'S3BucketPrefixName' # specify ssm parameter name
  Environment: 'prod'

tags:
  InfraDeploymentProcess: 'cf stack with git sync option for prod env'