AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket with a dynamically created name and apply a policy for access from EC2 instances'

Parameters:
  S3BucketPrefixName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ''
  Environment:
    Description: List of available environments
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stag
      - prod
    ConstraintDescription: Use valid environment [dev, stag, prod]

Mappings:
  EnvironmentLabel:
    dev:
      label: development
    stag:
      label: staging
    prod:
      label: production

Resources:
  S3BucketFiles:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !Sub
          - '${S3BucketPrefixName}-${UsedEnvironmentLabel}'
          - UsedEnvironmentLabel: !FindInMap [ EnvironmentLabel, !Ref Environment, label ]
      Tags:
        - Key: Name
          Value:
            !Sub
              - '${S3BucketPrefixName}-${UsedEnvironmentLabel}'
              - UsedEnvironmentLabel: !FindInMap [ EnvironmentLabel, !Ref Environment, label ]
        - Key: Environment
          Value: !FindInMap [ EnvironmentLabel, !Ref Environment, label ]

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketFiles
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - ec2.amazonaws.com
            Action:
              - s3:GetObject
            Resource: 
              !Sub
                - 'arn:${AWS::Partition}:s3:::${S3BucketPrefixName}-${UsedEnvironmentLabel}/*'
                - UsedEnvironmentLabel: !FindInMap [ EnvironmentLabel, !Ref Environment, label ]
